name: Check Box2D Last Push

on:
    schedule:
        - cron: '0 * * * *' # Runs every hour

jobs:
    check_last_push:
        runs-on: ubuntu-latest
        
        steps:
            - name: Fetch last push date/time from main branch
              id: compare_push
              run: |
                  # This grabs the date/time of the last commit on Box2D's main branch
                  last_push=$(curl -s https://api.github.com/repos/erincatto/box2d/branches/main | jq -r '.commit.commit.committer.date')
                  echo "Last push on main branch: $last_push"
                  
                  # If we failed to retrieve last_push (or it's literally "null"), exit early
                  if [ -z "$last_push" ] || [ "$last_push" = "null" ] || [ "$last_push" = "" ]; then
                    echo "No valid last push data received. Exiting."
                    echo "changed=false" >> $GITHUB_OUTPUT
                    exit 0
                  fi
                  
                  # 2. Fetch the previously recorded time from the raw file
                  old_push=$(curl -s https://raw.githubusercontent.com/HughPH/Box2D-dotnet-bindings/main/box2d_last_push.json | jq -r '.last_push')
                  # check for non-zero exit code
                  if [ $? -ne 0 ]; then
                    echo "No previous push data found. Assuming first run, or deleted file"
                    echo "changed=true" >> $GITHUB_OUTPUT
                    exit 0
                  fi                  
                  
                  echo "Previously recorded date/time: $old_push"
                  
                  # 3. Compare
                  if [ "$last_push" = "$old_push" ]; then
                    echo "No changes since last recorded push."
                    echo "changed=false" >> $GITHUB_OUTPUT
                  else
                    echo "Remote has changed since last recorded push."
                    # Indicate to subsequent steps that a change was detected
                    echo "changed=true" >> $GITHUB_OUTPUT
                    echo "lastpush=$last_push" >> $GITHUB_OUTPUT
                  fi

            - name: Checkout repository
              if: steps.compare_push.outputs.changed == 'true'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Update last_push file, commit & push
              if: steps.compare_push.outputs.changed == 'true'
              run: |                  
                  # Save the new push time to file
                  echo "{\"last_push\": \"${{ steps.compare_push.outputs.lastpush }}\"}" > box2d_last_push.json
                  
                  # Commit if it changed
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add box2d_last_push.json
                  
                  if git diff --staged --quiet; then
                    echo "No changes to commit."
                    exit 0
                  fi
                  
                  git commit -m "Detected change in Box2D main branch"
                  git push
                  
                  echo "Changes committed and pushed. Starting deployment..."
                  curl -X POST -H "Accept: application/vnd.github.everest-preview +json" \
                       -H "Authorization: token ${{ secrets.PAT }}" \
                       https://api.github.com/repos/HughPH/Box2D-dotnet-bindings/dispatches \
                       --data '{"event_type": "publish"}'
