name: Check Box2D Last Tag

on:
    schedule:
        - cron: '0 * * * *' # Runs every hour

jobs:
    check_last_tag:
        runs-on: ubuntu-latest
        
        steps:
            - name: Fetch latest tag from Box2D
              id: compare_tag
              run: |
                  response=$(curl -s -w "%{http_code}" -o response.json https://api.github.com/repos/erincatto/box2d/tags)
                  if [ "$response" -ne 200 ]; then
                    echo "Failed to fetch tags from GitHub API. HTTP status: $response"
                    echo "--- Response body ---"
                    cat response.json
                    echo "---------------------"
                    echo "changed=false" >> $GITHUB_OUTPUT
                    exit 0
                  fi
            
                  latest_tag=$(jq -r '.[0].name' < response.json 2>/dev/null)
            
                  if [ $? -ne 0 ] || [ -z "$latest_tag" ] || [ "$latest_tag" = "null" ]; then
                    echo "jq failed to parse tag or tag not found."
                    echo "--- Response body ---"
                    cat response.json
                    echo "---------------------"
                    echo "changed=false" >> $GITHUB_OUTPUT
                    exit 0
                  fi
            
                  echo "Latest tag: $latest_tag"
            
                  recorded_response=$(curl -s -w "%{http_code}" -o recorded_tag.json https://raw.githubusercontent.com/HughPH/Box2D-dotnet-bindings/main/box2d_last_tag.json)
                  if [ "$recorded_response" -ne 200 ]; then
                    echo "No previous tag data found or failed to fetch it. HTTP status: $recorded_response"
                    echo "changed=true" >> $GITHUB_OUTPUT
                    echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
                    exit 0
                  fi
            
                  recorded_tag=$(jq -r '.last_tag' < recorded_tag.json 2>/dev/null)
                  if [ $? -ne 0 ]; then
                    echo "Failed to parse previous tag JSON."
                    cat recorded_tag.json
                    echo "changed=true" >> $GITHUB_OUTPUT
                    echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
                    exit 0
                  fi
            
                  echo "Previously recorded tag: $recorded_tag"
            
                  if [ "$latest_tag" = "$recorded_tag" ]; then
                    echo "No new tag found."
                    echo "changed=false" >> $GITHUB_OUTPUT
                  else
                    echo "New tag detected!"
                    echo "changed=true" >> $GITHUB_OUTPUT
                    echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
                  fi
