name: Build on Push

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another pipeline
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            import { Octokit } from "https://esm.sh/@octokit/rest";
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            await octokit.repos.createDispatchEvent({
              owner: "HughPH",
              repo: "Box2D-dotnet-bindings",
              event_type: "publish"
            });