name: Build on Push

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another pipeline
        uses: octokit/request-action@v2.x
        id: trigger
        with:
          route: POST /repos/HughPH/Box2D-dotnet-bindings/actions/workflows/publish.yml/dispatches
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}