name: Build on Push

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another pipeline
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'HughPH',
              repo: 'Box2D-dotnet-bindings',
              workflow_id: 'publish.yml',
              ref: 'main'
            });