name: Runner Test

on:
    workflow_dispatch:

jobs:
    test-runner-path:
        runs-on: [self-hosted, Linux, X64]
        steps:
            - run: echo "Runner OK"
            - run: which aarch64-w64-mingw32-gcc
            - run: aarch64-w64-mingw32-gcc --version
            - run: echo $PATH
