name: Build on Box2D Push

on:
  repository_dispatch:
    types: [box2d-push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another pipeline
        uses: octokit/request-action@v2.x
        id: trigger
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish.yml/dispatches
          owner: HughPH
          repo: Box2D-dotnet-bindings
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}